---
title: "p8104"
author: "Qing Xu"
date: "December 8, 2017"
output:
  pdf_document: default
  html_document: default
  word_document: default
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(readxl)
library(data.table)
library(HH)
library(leaps)
library(car)
library(gridExtra)
library(knitr)
library(boot)
library(cvTools)
```

#Clean data
```{r}
#clean data and converting some variables
GH_data <- read_excel("GHProject_Dataset.xlsx") %>%
  clean_names() %>%
  group_by(patientid) %>%
  dplyr::mutate(is30dayreadmit = as.character(is30dayreadmit))

#count number of visit and select ICU=0
mul <- count(GH_data) 
GH_data_noICU <- left_join(GH_data,mul,by = "patientid") %>%
  filter(icu_flag == 0) %>%
  rename(num_visit = n) %>%
  data.table()

#select first visit
setkey(GH_data_noICU, patientid)
df <- GH_data_noICU[J(unique(patientid)), mult = "first"]

#select variables we interested
df <- df %>%
  dplyr::select(-c(loshours, admitdtm, icu_flag, facilityzip, postalcode, facilityname))
```


#Check the variables we interested in
```{r}
#create a list for checking the potential categorical predictors
category_check_list <- 
  df %>%
  dplyr::select(is30dayreadmit, evisit, mews, cindex, gender, race, religion, maritalstatus, insurancetype) %>%
  apply(2, table)
names(category_check_list) <- c("is30dayreadmit", "evisit", "mews", "cindex", "gender", 
                                "race", "religion", "maritalstatus", "insurancetype")
category_check_tbl <- tibble(variable = c("is30dayreadmit", "evisit", "mews", "cindex", "gender", 
                                          "race", "religion", "maritalstatus", "insurancetype"),
                             check_list = category_check_list)

#the summary data of potential continous predictors
data_summary <- 
  df %>%
    dplyr::select(-c(is30dayreadmit, evisit, mews, cindex, gender, race, 
                     religion, maritalstatus, insurancetype)) %>%
    dplyr::select(-c(patientid, visitid, losdays2, num_visit)) %>%
    gather(key = continuous_variable, value = value, ageyear:bpdiastolic) %>%
    group_by(continuous_variable) %>%
    summarise(min = min(value, na.rm = T),
              first_quantile = quantile(value,  probs = 0.25, na.rm = T),
              median = median(value, na.rm = T),
              third_quantile = quantile(value,  probs = 0.75, na.rm = T),
              max = max(value, na.rm = T))
kable(data_summary)

#we find the following four predictors should be combined
category_check_tbl$check_list[3]             #mews
category_check_tbl$check_list[4]             #cindex
category_check_tbl$check_list[6]             #race
category_check_tbl$check_list[7]             #religion
category_check_tbl$check_list[8]             #maritalstatus
```

```{r}
#combine the level we choose
df$mews<-replace(df$mews, df$mews>3, "further deterioration/immediate action required")
df$mews<-replace(df$mews, df$mews<4, "normal/increase caution")
df$cindex<-replace(df$cindex, df$cindex>4,"severe")
df$cindex<-replace(df$cindex, df$cindex==3|df$cindex==4,"moderate")
df$cindex<-replace(df$cindex, df$cindex==2|df$cindex==1,"mild")
df$cindex<-replace(df$cindex, df$cindex==0,"normal")
df$race<-replace(df$race, df$race=="Natv Hawaii/Pacf Isl","Other/Multiracial")
df$religion<-replace(df$religion, 
                     df$religion=="Angelican"|df$religion=="Hebrew"|df$religion=="Non Denominational"|df$religion=="Mormon",
                     "Other")
df$maritalstatus<-replace(df$maritalstatus, df$maritalstatus=="Civil Union","Married")
#change temperature and bmi
df$temperature[df$temperature < 24] <- NA
df$temperature[df$temperature > 47] <- NA
df$bmi[df$bmi < 7] <- NA
df$bmi[df$bmi > 50] <- NA
df$heartrate[df$heartrate > 220] <- NA
df$o2sat[df$o2sat > 200] <- NA
df$respirationrate[df$respirationrate > 50] <- NA
#omit the missing observations

# NAs 
#sum(is.na(df[,5]))  MEWS 163
#sum(is.na(df[,12])) maritalstatus 76
#sum(is.na(df[,13])) insurancetype 33
#sum(is.na(df[,14])) bmi 725

# "bpsystolic"     "o2sat"           "temperature"     "heartrate"       "respirationrate" "bpdiastolic"     "num_visit"      all have a few (<5) NAs
# impute these few ones by mean

df$bpdiastolic[is.na(df$bpdiastolic)] <- mean(df$bpdiastolic, na.rm = TRUE)
df$bpsystolic[is.na(df$bpsystolic)] <- mean(df$bpsystolic, na.rm = TRUE)
df$o2sat[is.na(df$o2sat)] <- mean(df$o2sat, na.rm = TRUE)
df$temperature[is.na(df$temperature)] <- mean(df$temperature, na.rm = TRUE)
df$heartrate[is.na(df$heartrate)] <- mean(df$heartrate, na.rm = TRUE)
df$respirationrate[is.na(df$respirationrate)] <- mean(df$respirationrate, na.rm = TRUE)

df <- df %>% dplyr::select(-bmi) %>% na.omit()
```

#transformation
```{r}
#histogram of outcome
outcome_nontran <- 
  ggplot(df,aes(x = losdays2))+
  geom_histogram(bins = 20) +
  ggtitle("histogram of length of days") + 
  theme(plot.title = element_text(hjust = 0.5))
outcome_tran <- ggplot(df,aes(x = log(losdays2)))+
  geom_histogram(bins = 15) +
  ggtitle("histogram of log(length of days)") + 
  theme(plot.title = element_text(hjust = 0.5))
grid.arrange(outcome_nontran, outcome_tran)
#use log of losdays2
df <- df %>%
  mutate(log_los=log(losdays2)) %>%
  dplyr::select(-patientid,-visitid,-losdays2,-num_visit)
#Now we have our final data for regression
```

#variables who are included
```{r}
lm_is<-lm(log_los~factor(is30dayreadmit),data=df) 
lm_mews<-lm(log_los~factor(mews),data=df) 
lm_cindex<-lm(log_los~cindex,data=df)
lm_evisit<-lm(log_los~evisit,data=df)
lm_ageyear<-lm(log_los~ageyear,data=df)
lm_gender<-lm(log_los~factor(gender),data=df) # not sig 
lm_race<-lm(log_los~factor(race),data=df)  #not sig
lm_religion<-lm(log_los~factor(religion),data=df) # only some levels sig
lm_maritalstatus<-lm(log_los~factor(maritalstatus),data=df) # not sig
lm_insurancetype<-lm(log_los~factor(insurancetype),data=df) # only some levels sig, kept in model
lm_tem<-lm(log_los~temperature,data=df) 
lm_hear<-lm(log_los~heartrate,data=df)
lm_res<-lm(log_los~respirationrate,data=df)
lm_bpd<-lm(log_los~bpdiastolic,data=df)
lm_bps<-lm(log_los~bpsystolic,data=df)
lm_o2<-lm(log_los~o2sat,data=df)

#remove bmi - too many NAs
lm_full<-lm(log_los~mews+is30dayreadmit+cindex+evisit+ageyear+temperature+heartrate+respirationrate+bpdiastolic+bpsystolic+o2sat + insurancetype,data=df)

# results from stepwise automatic
summary(step(lm_full, direction='both', trace = 0))


#select
best <- function(model, ...) 
{
  subsets <- regsubsets(formula(model), model.frame(model),nvmax=length(model$coefficients)-1, ...)
  subsets <- with(summary(subsets),
                  cbind(p = as.numeric(rownames(which)), which, rss, rsq, adjr2, cp, bic))
  
  return(subsets)
}  

# Select the 'best' 1 models of all subsets
round(best(lm_full, nbest = 1), 4) #remove mews and O2sta based on this output
```


```{r}
#fit the best model  and give a summary 
lm_best <- lm(log_los~ is30dayreadmit + cindex + evisit + ageyear + 
    temperature + heartrate + respirationrate + bpdiastolic + 
    bpsystolic + insurancetype, data = df)
summary(lm_best)
#give the diagnostics plots
par(mfrow=c(2,2))
plot(lm_best, which = 1:5)
#check the the 1607th, 768th, 1478th observation(patientid:477165, 558208, 1680385)
df[c(1607, 768, 1478),]
rstandard(lm_best)[c(1607, 768, 1478)]  #1607th, 1478th are outliers in Y, 768th is not an outlier


#first from the residuals vs leverage plot, we find that they are not outliers in X
rstandard(lm_best)[c(1607, 768, 1478)]  #they are outliers in Y, but their |ri|s are just a bit larger than 2.5

#since the QQplot show that there might be some outliers in Y, we can try to remove and find what happen

#find all the outliers in Y
outlier_y <- which(abs(rstandard(lm_best)) > 2.5)

outliers_df <- df[which(abs(rstandard(lm_best)) > 2.5),]

#now we check what happens in the outliers in Y
tbl_is30dayreadmit <- 
  bind_rows(table(df$is30dayreadmit)-table(outliers_df$is30dayreadmit),
            table(outliers_df$is30dayreadmit)) %>%
  mutate(data = c("data without outliers", "outlires")) %>%
  dplyr::select(data, everything())
chisq.test(tbl_is30dayreadmit[,-1])

tbl_cindex <- 
  bind_rows(table(df$cindex)-table(outliers_df$cindex),
            table(outliers_df$cindex)) %>%
  mutate(data = c("data without outliers", "outlires")) %>%
  dplyr::select(data, everything())
chisq.test(tbl_cindex[,-1])

tbl_evisit <- 
  bind_rows(table(df$evisit)-table(outliers_df$evisit),
            table(outliers_df$evisit)) %>%
  mutate(data = c("data without outliers", "outlires")) %>%
  dplyr::select(data, everything())
chisq.test(tbl_evisit[,-1])

tbl_insurancetype <- 
  bind_rows(table(df$insurancetype)-table(outliers_df$insurancetype),
            table(outliers_df$insurancetype)) %>%
  mutate(data = c("data without outliers", "outlires")) %>%
  dplyr::select(data, everything())
chisq.test(tbl_insurancetype[,-1])

#now we fit the model these points including the three influential cases
df_rm <- df[-outlier_y,]
lm_best_2 <- df_rm %>%
  lm(log_los~ is30dayreadmit + cindex + evisit + ageyear + 
    temperature + heartrate + respirationrate + bpdiastolic + 
    bpsystolic + insurancetype, data = .)
summary(lm_best_2)
plot(lm_best_2, which = 1:5)
#we find that the QQplot become better and R^2 become larger. So we decide to remove the outliers in Y


#test whether outlier is different with other data 
#use t-test to test the difference
t_function<-function(x,y){
  out<-x
rm<-y
p_value<-t.test(out,rm, var.equal=FALSE, paired=FALSE)[3]
return(p_value)
}
t_function(outliers_df$evisit,df_rm$evisit)
t_function(outliers_df$ageyear,df_rm$ageyear) #different,p-value=0.00033
t_function(outliers_df$bpsystolic,df_rm$bpsystolic)
t_function(outliers_df$o2sat ,df_rm$o2sat)
t_function(outliers_df$temperature,df_rm$temperature)
t_function(outliers_df$respirationrate,df_rm$respirationrate)
t_function(outliers_df$heartrate,df_rm$heartrate)
t_function(outliers_df$bpdiastolic,df_rm$bpdiastolic)

tibble(age=df_rm$ageyear,data=rep("exclude outlier",length(df_rm$ageyear))) %>%
  bind_rows(tibble(age=outliers_df$ageyear,data=rep("outlier",length(outliers_df$ageyear))) ) %>%
  group_by(data) %>%
  ggplot(aes(x=data,y=age),group=data)+
  geom_boxplot() +
  labs(title="Distribution of age in outliers and other")

tibble(log_los=df_rm$log_los,data=rep("exclude outlier",length(df_rm$log_los))) %>%
  bind_rows(tibble(log_los=outliers_df$log_los,data=rep("outlier",length(outliers_df$log_los))) ) %>%
  group_by(data) %>%
  ggplot(aes(x=data,y=exp(log_los)),group=data)+
  geom_boxplot() +
  labs(title="Distribution of Length of Stay in outliers and other")

```


#predictive capability by cross validation
```{r}
#LOOCV
#use a glm function to fit the lm model since we must use cv.glm to do LOOCV
glm_best <- glm(log_los~ is30dayreadmit + cindex + evisit + ageyear + 
    temperature + heartrate + respirationrate + bpdiastolic + 
    bpsystolic + insurancetype, data = df_rm)
#LOOCV and give the MSE
cv_err <- cv.glm(df_rm, glm_best)
cv_err$delta
#the MSE in our final model
anova(lm_best_2)$`Mean Sq`[11]
#we can find that the MSE in LOOCV is just slighter larger than the MSE in our final model
#Then we state that our model can be generalized well and have good predictive capability

#K-fold CV
#set up folds for cross-validation
folds <- cvFolds(nrow(df_rm), K = 10, R = 40)
# perform cross-validation for an LS regression model
cvFitLm <- cvLm(lm_best_2, cost = rtmspe, folds = folds, trim = 0.1)
#check the CV in this cross validation and the MSE in our final model and we find that they are close
cvFitLm
#Then we state that our model can be generalized well and have good predictive capability

#combine the result together
tibble(term = c("best model we choose", "N-fold", "10-fold"), MSE = c(anova(lm_best_2)$`Mean Sq`[11], cv_err$delta[1], cvFitLm$cv))
```


Final model Table
```{r, echo=FALSE}
variable_names <- c("Intercept", "
                    Is 30 Day Readmit or Not", 
                    "Charlson comorbidity index (moderate)",  
                    "Charlson comorbidity index (normal)",  
                    "Charlson comorbidity index (severe)", 
                    "Emergency Dept Visits",
                    "Age",
                    "Temperature",
                    "Heart Rate",
                    "Respiration Rate",
                    "Diastolic BP",
                    "Systolic BP",
                    "Insurance Type (Medicare)",
                    "Insurance Type (Private)")
coeff <- summary(lm_best_2)$coeff[,1]
std_err <- summary(lm_best_2)$coeff[,2]


conf_ints <- data.frame(confint(lm_best_2))
conf_ints  <- paste(round(conf_ints [,1], digits = 4), 
                     round(conf_ints [,2], digits = 4), 
                     sep=", ")
model_table <- cbind(variable_names, round(coeff, digits = 4), round(std_err, digits = 4), conf_ints)

row.names(model_table) <- c()

kable(model_table, col.names =  c("Variable", "Coefficients", "Standard Error", "95% Conf Intervals"))
```
